### ISSUE TITLE
NPE when running AEnumScrapper2.py

### ISSUE THREAD

**Issue by Totakeke101** [Treeki/CylindricalEarth#3]
I tried to run your scrapping script from the Ghidra, and the following error occurred:
> AEEnumScrapper2.py> Running...
Traceback (most recent call last):
  File "C:\Users\Totak\ghidra_scripts\AEEnumScrapper2.py", line 140, in <module>
    for ref in getReferencesTo(toAddr('BcsvHeader_isJPEnums')):
	at ghidra.program.database.references.ReferenceDBManager.getReferenceCountTo(ReferenceDBManager.java:890)
	at ghidra.program.flatapi.FlatProgramAPI.getReferencesTo(FlatProgramAPI.java:1978)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
java.lang.NullPointerException: java.lang.NullPointerException
AEEnumScrapper2.py> Finished!

Can I get any help?

**Comment by Treeki** [comment]
You need to find and define that function as it's used as a start point to find all of the functions necessary.

In v1.1.4, it's at 0x7101707c10.

If you're using another version, go to Search > Memory and enter the following sequence: `80 00 00 b4 08 2c 40 39 1f 01 00 71 e0 07 9f 1a c0 03 5f d6`

**Comment by Totakeke101** [comment]
Thanks for your help! It works nicely. Ah, also thanks for your works.
My question is done here. Closing!
